openapi: 3.0.3
info:
  title: Practice Backend
  version: 1.0.0
servers:
  - url: http://localhost:4000
paths:
  /ping:
    get:
      responses:
        '200':
          description: ok
  /auth/register:
    post:
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required: [email, name, password]
              properties:
                email: { type: string }
                name: { type: string }
                password: { type: string }
      responses:
        '201': { description: created }
        '409': { description: exists }
  /auth/login:
    post:
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required: [email, password]
              properties:
                email: { type: string }
                password: { type: string }
      responses:
        '200': { description: ok }
        '401': { description: invalid }
  /users:
    get:
      security: [{ bearerAuth: [] }]
      responses:
        '200': { description: ok }
        '401': { description: unauthorized }
  /users/search:
    get:
      security: [{ bearerAuth: [] }]
      parameters:
        - in: query
          name: q
          schema: { type: string }
      responses:
        '200': { description: ok }
components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
